export const GET_GRAPHS = 'GET_GRAPHS';
export const GET_GRAPH = 'GET_GRAPH';
export const CREATE_GRAPH = 'CREATE_GRAPH';
export const DELETE_GRAPH = 'DELETE_GRAPH';
export const UPDATE_GRAPH = 'UPDATE_GRAPH';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const CREATE_NODE = 'CREATE_NODE';
export const DELETE_NODE = 'DELETE_NODE';
export const UPDATE_NODE = 'UPDATE_NODE';
export const CREATE_LINK = 'CREATE_LINK';
export const DELETE_LINK = 'DELETE_LINK';
export const UPDATE_LINK = 'UPDATE_LINK';

export const CREATE_NODE_TYPE = 'CREATE_NODE_TYPE';
export const DELETE_NODE_TYPE = 'DELETE_NODE_TYPE';
export const UPDATE_NODE_TYPE = 'UPDATE_NODE_TYPE';
export const CREATE_LINK_TYPE = 'CREATE_LINK_TYPE';
export const DELETE_LINK_TYPE = 'DELETE_LINK_TYPE';
export const UPDATE_LINK_TYPE = 'UPDATE_LINK_TYPE';

export const UPDATE_NODE_POSITION = 'UPDATE_NODE_POSITION';
export const SET_ACTIVE_ELEMENT = 'SET_ACTIVE_ELEMENT';
export const UPDATE_ZOOM = 'UPDATE_ZOOM';
export const UPDATE_DEFAULT = 'UPDATE_DEFAULT';
export const SWITCH_NODETYPE_FILTER = 'SWITCH_NODETYPE_FILTER';
export const SWITCH_LINKTYPE_FILTER = 'SWITCH_LINKTYPE_FILTER';
