# Generated by Django 2.2.2 on 2020-11-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_graph_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='version',
            field=models.SmallIntegerField(default=0),
        ),
    ]
