# Generated by Django 2.2.2 on 2020-04-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_visualization'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='visualization',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Visualization',
        ),
    ]
