# Generated by Django 2.2.2 on 2020-04-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200420_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='model',
            field=models.TextField(null=True),
        ),
    ]
